version: '3.8'
services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test_db
      - POSTGRES_PASSWORD=123
    volumes:
      - "db-data:/var/lib/postgresql/data"

  app:
    build: .
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/test_db
      - JS_URL=http://localhost
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  db-data: