version: '3.8'
services:
  postgres:
    build:
      dockerfile: db/Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test_db
      - POSTGRES_PASSWORD=123
    volumes:
      - "db-data:/var/lib/postgresql/data"


  app:
    build:
      dockerfile: app/Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/test_db
      - JS_URL=http://localhost
    image: 'my-java-application'
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  db-data: