version: "3.7"
services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "fsync=off"]
  myapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
