spring:
  flyway:
    enabled: true
  application:
    name: Users API
  datasource:
    url: "jdbc:postgresql://localhost:5432/test_db?currentSchema=test"
    username: "test"
    password: "123"
    driver-class-name: org.postgresql.Driver
server:
  port: 8080