CREATE SCHEMA IF NOT EXISTS public;

CREATE SEQUENCE IF NOT EXISTS public.user_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS public.user (
  id INTEGER DEFAULT nextval('public.user_id_seq'::regclass) PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL
);