name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the JAR
        run: gradle build

      - name: Set up Docker
        uses: docker/setup-action@v1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag test-api:$(date +%s)
