name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache project files
        uses: actions/cache@v2
        with:
          path: /app
          key: ${{ runner.os }}-gradle-${{ hashFiles('/app/build.gradle') }}

      - name: Check code
        run: gradle check

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag test-api:$(date +%s)

      - name: Check Docker image
        run: docker scan test-api:$(date +%s)