name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test_db

    steps:
      - uses: actions/checkout@v3

      - name: Build the JAR
        run: gradle build

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag test-api:$(date +%s)