name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clear Docker cache
        run: docker builder prune -a -f

      - name: Build the JAR
        run: gradle build

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag test-api:$(date +%s)
